#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/aeris_db
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=${DB_USER:root}
#spring.datasource.password=${DB_PASSWORD:root}
#
## 2. Hard-set the Dialect (This fixes your "Unable to determine Dialect" error)
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
## 3. Handle Render's dynamic port
#server.port=${PORT:8080}
gemini.api.key=AIzaSyC1s0gGKVOlBl66hzbE5bqYM-jMUPeGBDg











spring.datasource.url=jdbc:mysql://localhost:3306/aeris_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#gemini.api.key=AIzaSyC1s0gGKVOlBl66hzbE5bqYM-jMUPeGBDg